### ISSUE TITLE
chore: minor improvements

### ISSUE THREAD

**Issue by pranshuchittora** [fnplus/buildathon#1]
Great work @amritavarshi :tada: 

Few suggestions

- [x]  Add favicon
- [x] Change the colour of the nav item when hovered.
- [x] View breaks on the mobile devices

![Screenshot from 2019-06-05 07-27-00](https://user-images.githubusercontent.com/32242596/58924938-5fc88680-8763-11e9-9ad2-9eebb09cec63.png)

**Comment by xlogix** [comment]
@amritavarshi

**Comment by amritavarshi** [comment]
I've added favicon, the site is mobile friendly. And changed the nav item colour to black when hovered.
